# Generated by Django 3.2.9 on 2022-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
